<?php

$delement_antivirus_default_option = [
    'scan_path' => '#DOCUMENT_ROOT#',
    'scan_profile' => 'standard',
    'profile' => 'balanced',
    'action' => 'report',
    'dry_run' => 'Y',
    'quarantine_path' => '#DOCUMENT_ROOT#/bitrix/tmp/delement.antivirus/quarantine',
    'signatures_path' => '',
    'exclude_paths' => "/bitrix/cache/\n/bitrix/managed_cache/\n/bitrix/stack_cache/\n/bitrix/html_pages/\n/upload/resize_cache/\n/bitrix/tmp/delement.antivirus/\n/bitrix/modules/delement.antivirus/",
    'batch_size' => '50',
    'max_file_size_mb' => '100',
    'enable_common_strings_prefilter' => 'Y',
    'enable_normalized_hash' => 'Y',
    'normalized_hash_max_file_size_mb' => '5',
    'enable_ast_analysis' => 'Y',
    'ast_max_file_size' => '1048576',
    'enable_entropy_analyzer' => 'N',
    'enable_entropy_in_deep_profile' => 'Y',
    'entropy_min_length' => '200',
    'entropy_threshold' => '4.7',
    'entropy_context_window' => '300',
    'enable_url_analyzer' => 'Y',
    'suspicious_domains_path' => '#DOCUMENT_ROOT#/bitrix/modules/delement.antivirus/var/signatures/suspicious_domains.json',
    'enable_hash_db' => 'Y',
    'malware_hashes_path' => '#DOCUMENT_ROOT#/bitrix/modules/delement.antivirus/var/signatures/malware_hashes.json',
    'malware_hash_prefixes_path' => '#DOCUMENT_ROOT#/bitrix/modules/delement.antivirus/var/signatures/malware_hash_prefixes.json',
    'malware_hash_prefix_length' => '8',
    'enable_bitrix_db_scan' => 'N',
    'scan_agents' => 'N',
    'panelica_source_path' => '',
    'panelica_download_url' => 'https://github.com/Panelica/malware-signatures',
    'panelica_last_import_at' => '',
    'panelica_imported_count' => '0',
    'panelica_source_commit' => '',
    'panelica_source_license' => '',
];
