<?php

use Delement\Antivirus\Detection\Severity;

return [
    [
        'id' => 'bitrix_php_in_upload',
        'category' => 'bitrix_specific',
        'severity' => Severity::HIGH,
        'score' => 8,
        'path_contains' => '/upload/',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7'],
    ],
    [
        'id' => 'bitrix_authorize_hardcoded_id',
        'category' => 'bitrix_specific',
        'severity' => Severity::HIGH,
        'score' => 8,
        'pattern' => '/\$USER\s*->\s*Authorize\s*\(\s*\d+\s*\)/i',
        'common_strings' => ['Authorize'],
        'extensions' => ['php', 'phtml', 'phtm', 'inc'],
    ],
    [
        'id' => 'bitrix_init_dynamic_execution',
        'category' => 'bitrix_specific',
        'severity' => Severity::HIGH,
        'score' => 7,
        'pattern' => '/\b(eval|assert|shell_exec|exec|system|passthru)\s*\(/i',
        'common_strings' => ['eval', 'assert', 'shell_exec', 'exec', 'system', 'passthru'],
        'path_equals' => '/bitrix/php_interface/init.php',
        'extensions' => ['php'],
    ],
    [
        'id' => 'bitrix_include_from_upload',
        'category' => 'bitrix_specific',
        'severity' => Severity::HIGH,
        'score' => 7,
        'pattern' => '/\b(include|require|include_once|require_once)\s*\(?\s*[^;]*(\/upload\/|["\']upload\/)/i',
        'common_strings' => ['upload'],
        'extensions' => ['php', 'phtml', 'phtm', 'inc'],
    ],
    [
        'id' => 'bitrix_suspicious_access_php',
        'category' => 'bitrix_specific',
        'severity' => Severity::MEDIUM,
        'score' => 4,
        'pattern' => '/\b(eval|base64_decode|shell_exec|assert|file_put_contents)\s*\(/i',
        'common_strings' => ['eval', 'base64_decode', 'shell_exec', 'assert', 'file_put_contents'],
        'path_equals' => '/.access.php',
        'extensions' => ['php'],
    ],
    [
        'id' => 'bitrix_event_handler_dynamic_exec',
        'category' => 'bitrix_specific',
        'severity' => Severity::HIGH,
        'score' => 6,
        'pattern' => '/(AddEventHandler|registerEventHandler)[^;]*(eval|assert|shell_exec|exec|system|base64_decode)/is',
        'common_strings' => ['AddEventHandler', 'registerEventHandler', 'eval', 'assert', 'shell_exec', 'exec', 'system', 'base64_decode'],
        'extensions' => ['php', 'phtml', 'phtm', 'inc'],
    ],
    [
        'id' => 'bitrix_upload_to_executable',
        'category' => 'bitrix_specific',
        'severity' => Severity::HIGH,
        'score' => 6,
        'pattern' => '/move_uploaded_file\s*\([^;]+\.(php|phtml|php3|php4|php5|php7)[\'"]/i',
        'common_strings' => ['move_uploaded_file'],
        'extensions' => ['php', 'phtml', 'phtm', 'inc'],
    ],
];
