<?php

use Delement\Antivirus\Detection\Severity;

return [
    [
        'id' => 'php_eval',
        'category' => 'php_code_execution',
        'severity' => Severity::HIGH,
        'score' => 5,
        'pattern' => '/\beval\s*\(/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_assert',
        'category' => 'php_code_execution',
        'severity' => Severity::HIGH,
        'score' => 4,
        'pattern' => '/\bassert\s*\(/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_create_function',
        'category' => 'php_code_execution',
        'severity' => Severity::HIGH,
        'score' => 4,
        'pattern' => '/\bcreate_function\s*\(/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_shell_exec',
        'category' => 'php_code_execution',
        'severity' => Severity::HIGH,
        'score' => 5,
        'pattern' => '/\b(shell_exec|exec|system|passthru|proc_open|popen|pcntl_exec)\s*\(/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_base64_decode',
        'category' => 'php_obfuscation',
        'severity' => Severity::MEDIUM,
        'score' => 2,
        'pattern' => '/\bbase64_decode\s*\(/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_obfuscation_helpers',
        'category' => 'php_obfuscation',
        'severity' => Severity::MEDIUM,
        'score' => 2,
        'pattern' => '/\b(gzinflate|gzuncompress|str_rot13)\s*\(/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_hex_pack',
        'category' => 'php_obfuscation',
        'severity' => Severity::MEDIUM,
        'score' => 3,
        'pattern' => '/\bpack\s*\(\s*["\']H\*["\']/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_request_callable',
        'category' => 'webshell_behavior',
        'severity' => Severity::HIGH,
        'score' => 6,
        'pattern' => '/\$_(GET|POST|REQUEST|COOKIE)\s*\[[^\]]+\]\s*\(/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_dangerous_include_from_request',
        'category' => 'filesystem_abuse',
        'severity' => Severity::HIGH,
        'score' => 6,
        'pattern' => '/\b(include|require|include_once|require_once)\s*\(?\s*\$_(GET|POST|REQUEST|COOKIE)/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_input_write',
        'category' => 'webshell_behavior',
        'severity' => Severity::HIGH,
        'score' => 6,
        'pattern' => '/file_put_contents\s*\(\s*["\']php:\/\/input["\']\s*,/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_wrapper_filter',
        'category' => 'filesystem_abuse',
        'severity' => Severity::HIGH,
        'score' => 5,
        'pattern' => '/php:\/\/filter/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc', 'txt'],
    ],
    [
        'id' => 'php_preg_replace_eval',
        'category' => 'php_code_execution',
        'severity' => Severity::HIGH,
        'score' => 5,
        'pattern' => '/preg_replace\s*\(\s*[\'"].*\/e[\'"]\s*,/i',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc'],
    ],
    [
        'id' => 'php_long_base64',
        'category' => 'php_obfuscation',
        'severity' => Severity::MEDIUM,
        'score' => 3,
        'pattern' => '/[A-Za-z0-9+\/]{160,}={0,2}/',
        'extensions' => ['php', 'phtml', 'phtm', 'php3', 'php4', 'php5', 'php6', 'php7', 'inc', 'js', 'html', 'htm', 'txt'],
    ],
];
